In [1]:
import pandas as pd
import numpy as np

# Load data
df = pd.read_csv("water_quality_dataset_100k_new.csv")

# Basic info

In [2]:
print(df.shape)

(100000, 24)

In [3]:
print(df.head())

     Index        pH      Iron   Nitrate    Chloride           Lead      Zinc  \
0  3343584  7.262136  0.002857  5.965704  245.101184   6.679537e-44  0.702867
1  4332797  6.827967  0.000356  8.650092  261.948686  2.751868e-159  0.205934
2  2580354       NaN  0.000063       NaN  176.192348            NaN  0.896104
3   484305  7.782600  0.051721  3.747001  224.053938  1.513023e-136  0.088500
4  1026518  7.627800  0.000172  7.988966   89.478315   3.450032e-76  0.402281

            Color  Turbidity  Fluoride  ...  Chlorine     Manganese  \
0    Faint Yellow   0.014223  0.583591  ...  2.835370  8.067879e-03
1       Colorless   0.339881  2.214786  ...  3.228036  4.245956e-05
2  Near Colorless   0.122076  1.566183  ...  2.863932  1.646600e-03
3       Colorless   0.209460  0.693032  ...  4.195383  5.283502e-11
4       Colorless   0.520102  1.130603  ...  4.004640  9.799640e-03

   Total Dissolved Solids     Source  Water Temperature  Air Temperature  \
0              153.126744     Spring          11.179752        55.340114
1              260.391845     Ground          12.573723        80.335206
2              131.984171  Reservoir          12.702576        81.535521
3              447.051626        NaN          13.009862        72.845282
4              395.187898     Ground          17.727374        36.844691

      Month   Day  Time of Day  Target
0    August  20.0         17.0       0
1      June  26.0          2.0       1
2   January   4.0         16.0       0
3       May  13.0          1.0       0
4  December  25.0         18.0       0

[5 rows x 24 columns]

In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 24 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Index                   100000 non-null  int64
 1   pH                      97979 non-null   float64
 2   Iron                    99328 non-null   float64
 3   Nitrate                 98204 non-null   float64
 4   Chloride                97045 non-null   float64
 5   Lead                    99571 non-null   float64
 6   Zinc                    97439 non-null   float64
 7   Color                   99901 non-null   object
 8   Turbidity               99167 non-null   float64
 9   Fluoride                96784 non-null   float64
 10  Copper                  96785 non-null   float64
 11  Odor                    97034 non-null   float64
 12  Sulfate                 96723 non-null   float64
 13  Conductivity            97215 non-null   float64
 14  Chlorine                98992 non-null   float64
 15  Manganese               98170 non-null   float64
 16  Total Dissolved Solids  99961 non-null   float64
 17  Source                  98471 non-null   object
 18  Water Temperature       97190 non-null   float64
 19  Air Temperature         99521 non-null   float64
 20  Month                   98377 non-null   object
 21  Day                     98309 non-null   float64
 22  Time of Day             98064 non-null   float64
 23  Target                  100000 non-null  int64
dtypes: float64(19), int64(2), object(3)
memory usage: 18.3+ MB
None

In [5]:
print(df.isnull().sum())

Index                        0
pH                        2021
Iron                       672
Nitrate                   1796
Chloride                  2955
Lead                       429
Zinc                      2561
Color                       99
Turbidity                  833
Fluoride                  3216
Copper                    3215
Odor                      2966
Sulfate                   3277
Conductivity              2785
Chlorine                  1008
Manganese                 1830
Total Dissolved Solids      39
Source                    1529
Water Temperature         2810
Air Temperature            479
Month                     1623
Day                       1691
Time of Day               1936
Target                       0
dtype: int64

In [6]:
# Fill missing numerical values with mean
for col in df.select_dtypes(include=['float64', 'int64']).columns:
    df[col] = df[col].fillna(df[col].mean())

In [7]:

# Fill missing numerical values with mean
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].fillna(df[col].mode().iloc[0])

In [8]:
df

,Index,pH,Iron,Nitrate,Chloride,Lead,Zinc,Color,Turbidity,Fluoride,...,Chlorine,Manganese,Total Dissolved Solids,Source,Water Temperature,Air Temperature,Month,Day,Time of Day,Target
0,3343584,7.262136,2.857248e-03,5.965704,245.101184,6.679537e-44,0.702867,Faint Yellow,0.014223,0.583591,...,2.835370,8.067879e-03,153.126744,Spring,11.179752,55.340114,August,20.0,17.0,0
1,4332797,6.827967,3.555528e-04,8.650092,261.948686,2.751868e-159,0.205934,Colorless,0.339881,2.214786,...,3.228036,4.245956e-05,260.391845,Ground,12.573723,80.335206,June,26.0,2.0,1
2,2580354,7.450048,6.303493e-05,6.154743,176.192348,1.759505e-03,0.896104,Near Colorless,0.122076,1.566183,...,2.863932,1.646600e-03,131.984171,Reservoir,12.702576,81.535521,January,4.0,16.0,0
3,484305,7.782600,5.172140e-02,3.747001,224.053938,1.513023e-136,0.088500,Colorless,0.209460,0.693032,...,4.195383,5.283502e-11,447.051626,Ground,13.009862,72.845282,May,13.0,1.0,0
4,1026518,7.627800,1.721911e-04,7.988966,89.478315,3.450032e-76,0.402281,Colorless,0.520102,1.130603,...,4.004640,9.799640e-03,395.187898,Ground,17.727374,36.844691,December,25.0,18.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,4868170,6.878051,4.117124e-07,5.322810,108.110638,8.696207e-159,3.182844,Colorless,0.278222,1.282346,...,3.844900,3.612888e-03,490.345588,Lake,9.796617,38.218949,May,21.0,7.0,0
99996,468267,6.234022,1.117469e-01,17.328060,419.511947,3.996521e-146,0.279021,Yellow,0.152766,1.119400,...,2.896578,3.589283e-03,355.272379,Well,15.855275,63.903902,March,18.0,12.0,0
99997,3189489,7.861995,3.820164e-05,4.304552,215.233572,2.909526e-124,0.009500,Near Colorless,0.027866,0.093040,...,2.131950,1.754100e-03,337.180755,River,37.648185,72.763230,May,15.0,12.0,0
99998,4503294,7.865141,4.720492e-02,1.782478,192.690548,8.000041e-221,0.303846,Colorless,0.004299,0.423846,...,3.251744,1.972004e-02,307.239395,Stream,7.719304,46.404757,December,22.0,17.0,0
99999,3456164,8.590040,3.168677e-04,4.373577,196.374090,2.664295e-03,0.483866,Near Colorless,1.262112,0.943935,...,3.838088,2.872968e-01,164.660271,Reservoir,12.657137,63.647430,November,12.0,19.0,1

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 24 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Index                   100000 non-null  int64
 1   pH                      100000 non-null  float64
 2   Iron                    100000 non-null  float64
 3   Nitrate                 100000 non-null  float64
 4   Chloride                100000 non-null  float64
 5   Lead                    100000 non-null  float64
 6   Zinc                    100000 non-null  float64
 7   Color                   100000 non-null  object
 8   Turbidity               100000 non-null  float64
 9   Fluoride                100000 non-null  float64
 10  Copper                  100000 non-null  float64
 11  Odor                    100000 non-null  float64
 12  Sulfate                 100000 non-null  float64
 13  Conductivity            100000 non-null  float64
 14  Chlorine                100000 non-null  float64
 15  Manganese               100000 non-null  float64
 16  Total Dissolved Solids  100000 non-null  float64
 17  Source                  100000 non-null  object
 18  Water Temperature       100000 non-null  float64
 19  Air Temperature         100000 non-null  float64
 20  Month                   100000 non-null  object
 21  Day                     100000 non-null  float64
 22  Time of Day             100000 non-null  float64
 23  Target                  100000 non-null  int64
dtypes: float64(19), int64(2), object(3)
memory usage: 18.3+ MB

In [10]:
df["ph_cat"] = pd.cut(df["pH"], bins=[0, 1.5, 3.0, 4.5, 6.0, np.inf], labels=[1, 2, 3, 4, 5])

In [11]:
from sklearn.model_selection import StratifiedShuffleSplit

# Assume income_cat is a column in the dataset created from median_income
split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)

for train_index, test_index in split.split(df, df["ph_cat"]):
    strat_train_set = df.loc[train_index]
    strat_test_set = df.loc[test_index]

In [12]:
#lets Drop/Remove   the income _cat column
for sett in(strat_train_set,strat_test_set):
    sett.drop("ph_cat",axis=1,inplace=True)

In [13]:
 df=strat_train_set.copy()

In [14]:
df

,Index,pH,Iron,Nitrate,Chloride,Lead,Zinc,Color,Turbidity,Fluoride,...,Chlorine,Manganese,Total Dissolved Solids,Source,Water Temperature,Air Temperature,Month,Day,Time of Day,Target
54075,5359178,5.572276,4.175687e-09,2.851874,119.498934,7.489968e-97,3.636122,Near Colorless,0.051736,0.917626,...,2.405260,3.996315e-02,117.892186,Well,23.214949,67.340192,October,23.0,13.0,0
5702,2292278,6.938190,7.898426e-04,8.154365,162.489970,6.105299e-122,6.493891,Light Yellow,0.001859,0.206149,...,4.381704,4.883054e-03,17.871919,Aquifer,9.214959,66.280711,August,3.0,8.0,1
69940,1493874,6.352367,1.137835e-03,10.317333,130.162607,1.843087e-97,1.583133,Colorless,0.307849,3.940888,...,5.183672,2.359729e+00,14.629399,Ground,8.668647,64.295445,September,2.0,18.0,1
32267,1037475,9.029656,1.463985e-03,8.180221,521.857649,3.544747e-55,3.217883,Faint Yellow,0.048688,0.822867,...,4.782399,3.676510e-04,63.194050,Well,28.992138,55.572660,August,28.0,1.0,0
83955,2558197,7.193711,8.514599e-09,6.527220,185.860211,1.482446e-88,0.842889,Colorless,0.002837,2.972471,...,2.751774,1.636931e-02,354.298537,Ground,15.987721,87.330365,December,19.0,18.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90065,4818601,6.573393,5.251983e-04,7.274409,141.463977,1.060525e-87,0.764373,Light Yellow,0.001115,0.352851,...,2.888131,1.210334e-05,461.636564,River,31.972167,58.790909,August,13.0,11.0,0
38949,1404704,7.962873,2.195415e-01,6.290344,161.968868,3.244828e-62,2.825339,Colorless,0.574684,0.135437,...,3.088898,5.189488e-05,122.729477,Reservoir,6.328990,75.019476,January,5.0,6.0,0
75358,5267280,8.411046,2.817521e-02,5.808963,139.396812,3.770386e-24,0.224935,Faint Yellow,0.384634,0.694815,...,3.485823,7.607918e-05,436.090122,Lake,8.752678,72.827572,December,11.0,1.0,0
43225,88740,8.346611,6.564384e-16,8.302285,224.506537,9.335712e-10,2.353626,Colorless,0.003429,0.152217,...,3.628156,3.236652e-09,250.616954,Spring,7.454319,45.723301,August,12.0,20.0,0
81403,5083858,7.624410,2.900757e-13,9.501549,255.004244,9.201041e-70,0.116441,Near Colorless,0.072364,0.785414,...,2.556043,1.651802e-01,315.748633,Spring,17.796024,31.289802,October,25.0,4.0,1

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 80000 entries, 54075 to 81403
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Index                   80000 non-null  int64
 1   pH                      80000 non-null  float64
 2   Iron                    80000 non-null  float64
 3   Nitrate                 80000 non-null  float64
 4   Chloride                80000 non-null  float64
 5   Lead                    80000 non-null  float64
 6   Zinc                    80000 non-null  float64
 7   Color                   80000 non-null  object
 8   Turbidity               80000 non-null  float64
 9   Fluoride                80000 non-null  float64
 10  Copper                  80000 non-null  float64
 11  Odor                    80000 non-null  float64
 12  Sulfate                 80000 non-null  float64
 13  Conductivity            80000 non-null  float64
 14  Chlorine                80000 non-null  float64
 15  Manganese               80000 non-null  float64
 16  Total Dissolved Solids  80000 non-null  float64
 17  Source                  80000 non-null  object
 18  Water Temperature       80000 non-null  float64
 19  Air Temperature         80000 non-null  float64
 20  Month                   80000 non-null  object
 21  Day                     80000 non-null  float64
 22  Time of Day             80000 non-null  float64
 23  Target                  80000 non-null  int64
dtypes: float64(19), int64(2), object(3)
memory usage: 15.3+ MB

In [16]:
sample= strat_train_set.drop("Target", axis=1)
sample_labels = strat_train_set["Target"].copy()

In [17]:
sample.info()

<class 'pandas.core.frame.DataFrame'>
Index: 80000 entries, 54075 to 81403
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Index                   80000 non-null  int64
 1   pH                      80000 non-null  float64
 2   Iron                    80000 non-null  float64
 3   Nitrate                 80000 non-null  float64
 4   Chloride                80000 non-null  float64
 5   Lead                    80000 non-null  float64
 6   Zinc                    80000 non-null  float64
 7   Color                   80000 non-null  object
 8   Turbidity               80000 non-null  float64
 9   Fluoride                80000 non-null  float64
 10  Copper                  80000 non-null  float64
 11  Odor                    80000 non-null  float64
 12  Sulfate                 80000 non-null  float64
 13  Conductivity            80000 non-null  float64
 14  Chlorine                80000 non-null  float64
 15  Manganese               80000 non-null  float64
 16  Total Dissolved Solids  80000 non-null  float64
 17  Source                  80000 non-null  object
 18  Water Temperature       80000 non-null  float64
 19  Air Temperature         80000 non-null  float64
 20  Month                   80000 non-null  object
 21  Day                     80000 non-null  float64
 22  Time of Day             80000 non-null  float64
dtypes: float64(19), int64(1), object(3)
memory usage: 14.6+ MB

In [18]:
print(sample.columns.tolist())
print(sample.dtypes)

['Index', 'pH', 'Iron', 'Nitrate', 'Chloride', 'Lead', 'Zinc', 'Color', 'Turbidity', 'Fluoride', 'Copper', 'Odor', 'Sulfate', 'Conductivity', 'Chlorine', 'Manganese', 'Total Dissolved Solids', 'Source', 'Water Temperature', 'Air Temperature', 'Month', 'Day', 'Time of Day']
Index                       int64
pH                        float64
Iron                      float64
Nitrate                   float64
Chloride                  float64
Lead                      float64
Zinc                      float64
Color                      object
Turbidity                 float64
Fluoride                  float64
Copper                    float64
Odor                      float64
Sulfate                   float64
Conductivity              float64
Chlorine                  float64
Manganese                 float64
Total Dissolved Solids    float64
Source                     object
Water Temperature         float64
Air Temperature           float64
Month                      object
Day                       float64
Time of Day               float64
dtype: object

In [19]:
# Separate numeric and object columns
numeric_cols = sample.select_dtypes(include=['float64', 'int64']).columns

object_cols = sample.select_dtypes(include=['object']).columns

print("Numeric Columns:", numeric_cols)
print("Object Columns:", object_cols)

Numeric Columns: Index(['Index', 'pH', 'Iron', 'Nitrate', 'Chloride', 'Lead', 'Zinc',
       'Turbidity', 'Fluoride', 'Copper', 'Odor', 'Sulfate', 'Conductivity',
       'Chlorine', 'Manganese', 'Total Dissolved Solids', 'Water Temperature',
       'Air Temperature', 'Day', 'Time of Day'],
      dtype='object')
Object Columns: Index(['Color', 'Source', 'Month'], dtype='object')

In [20]:
from sklearn.impute import SimpleImputer

In [21]:
num_imputer = SimpleImputer(strategy='mean')  # You can use median if needed
sample[numeric_cols] = num_imputer.fit_transform(sample[numeric_cols])

In [22]:
obj_imputer = SimpleImputer(strategy='most_frequent')  # Use mode
sample[object_cols] = obj_imputer.fit_transform(sample[object_cols])

In [27]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
sample['Month'] = le.fit_transform(sample['Month'])
sample['Source'] = le.fit_transform(sample['Source'])
sample['Color'] = le.fit_transform(sample['Color'])

In [28]:
sample

,Index,pH,Iron,Nitrate,Chloride,Lead,Zinc,Color,Turbidity,Fluoride,...,Conductivity,Chlorine,Manganese,Total Dissolved Solids,Source,Water Temperature,Air Temperature,Month,Day,Time of Day
54075,5359178.0,5.572276,4.175687e-09,2.851874,119.498934,7.489968e-97,3.636122,3,0.051736,0.917626,...,267.472862,2.405260,3.996315e-02,117.892186,7,23.214949,67.340192,10,23.0,13.0
5702,2292278.0,6.938190,7.898426e-04,8.154365,162.489970,6.105299e-122,6.493891,2,0.001859,0.206149,...,495.191505,4.381704,4.883054e-03,17.871919,0,9.214959,66.280711,1,3.0,8.0
69940,1493874.0,6.352367,1.137835e-03,10.317333,130.162607,1.843087e-97,1.583133,0,0.307849,3.940888,...,496.087614,5.183672,2.359729e+00,14.629399,1,8.668647,64.295445,11,2.0,18.0
32267,1037475.0,9.029656,1.463985e-03,8.180221,521.857649,3.544747e-55,3.217883,1,0.048688,0.822867,...,460.795027,4.782399,3.676510e-04,63.194050,7,28.992138,55.572660,1,28.0,1.0
83955,2558197.0,7.193711,8.514599e-09,6.527220,185.860211,1.482446e-88,0.842889,0,0.002837,2.972471,...,283.988925,2.751774,1.636931e-02,354.298537,1,15.987721,87.330365,2,19.0,18.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90065,4818601.0,6.573393,5.251983e-04,7.274409,141.463977,1.060525e-87,0.764373,2,0.001115,0.352851,...,231.327254,2.888131,1.210334e-05,461.636564,4,31.972167,58.790909,1,13.0,11.0
38949,1404704.0,7.962873,2.195415e-01,6.290344,161.968868,3.244828e-62,2.825339,0,0.574684,0.135437,...,432.775652,3.088898,5.189488e-05,122.729477,3,6.328990,75.019476,4,5.0,6.0
75358,5267280.0,8.411046,2.817521e-02,5.808963,139.396812,3.770386e-24,0.224935,1,0.384634,0.694815,...,425.602265,3.485823,7.607918e-05,436.090122,2,8.752678,72.827572,2,11.0,1.0
43225,88740.0,8.346611,6.564384e-16,8.302285,224.506537,9.335712e-10,2.353626,0,0.003429,0.152217,...,266.315096,3.628156,3.236652e-09,250.616954,5,7.454319,45.723301,1,12.0,20.0
81403,5083858.0,7.624410,2.900757e-13,9.501549,255.004244,9.201041e-70,0.116441,3,0.072364,0.785414,...,444.590553,2.556043,1.651802e-01,315.748633,5,17.796024,31.289802,10,25.0,4.0

In [29]:
from sklearn.preprocessing import StandardScaler
#standardized_value = (x - mean) / std
scaler = StandardScaler()
sample_scaled = scaler.fit_transform(sample)
sample_scaled=pd.DataFrame(sample_scaled,columns=sample.columns,index=sample.index)
sample_scaled

,Index,pH,Iron,Nitrate,Chloride,Lead,Zinc,Color,Turbidity,Fluoride,...,Conductivity,Chlorine,Manganese,Total Dissolved Solids,Source,Water Temperature,Air Temperature,Month,Day,Time of Day
54075,1.392733,-2.127777,-0.270142,-1.029073,-0.967376,-0.047238,1.361767,0.937349,-0.508493,-0.056864,...,-0.840806,-1.163030,-0.144528,-0.959312,1.540449,0.363253,0.403621,1.295206,0.831531,0.217478
5702,-0.395634,-0.579260,-0.268468,0.623065,-0.325077,-0.047238,3.231735,0.221911,-0.563000,-0.940545,...,0.374196,1.545320,-0.221383,-1.600711,-1.510225,-0.887780,0.345087,-1.328609,-1.457477,-0.512560
69940,-0.861198,-1.243399,-0.267731,1.296998,-0.808058,-0.047238,0.018403,-1.208965,-0.228606,3.698142,...,0.378977,2.644268,4.937691,-1.621504,-1.074415,-0.936598,0.235406,1.586741,-1.571927,0.947516
32267,-1.127333,1.791806,-0.267040,0.631121,5.043983,-0.047238,1.088094,-0.493527,-0.511823,-0.174557,...,0.190672,2.094398,-0.231275,-1.310074,1.540449,0.879500,-0.246504,-1.328609,1.403783,-1.534613
83955,-0.240571,-0.289579,-0.270142,0.116083,0.024081,-0.047238,-0.465973,-1.208965,-0.561931,2.495332,...,-0.752684,-0.688197,-0.196218,0.556690,-1.074415,-0.282569,1.508025,-1.037074,0.373729,0.947516
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90065,1.077512,-0.992824,-0.269029,0.348890,-0.639212,-0.047238,-0.517350,0.221911,-0.563813,-0.758335,...,-1.033663,-0.501344,-0.232054,1.245016,0.233017,1.145795,-0.068705,-1.328609,-0.312973,-0.074537
38949,-0.913195,0.582409,0.195076,0.042278,-0.332863,-0.047238,0.831235,-1.208965,0.062999,-1.028372,...,0.041174,-0.226230,-0.231967,-0.928292,-0.202794,-1.145669,0.827881,-0.454004,-1.228576,-0.804575
75358,1.339145,1.090497,-0.210438,-0.107710,-0.670096,-0.047238,-0.870328,-0.493527,-0.144692,-0.333603,...,0.002900,0.317681,-0.231914,1.081194,-0.638604,-0.929089,0.706784,-1.037074,-0.541874,-1.534613
43225,-1.680558,1.017447,-0.270142,0.669154,0.601469,-0.047238,0.522571,-1.208965,-0.561285,-1.007531,...,-0.846984,0.512722,-0.232081,-0.108188,0.668828,-1.045110,-0.790655,-1.328609,-0.427423,1.239531
81403,1.232189,0.198698,-0.270142,1.042818,1.057113,-0.047238,-0.941321,0.937349,-0.485950,-0.221076,...,0.104213,-0.956410,0.129802,0.309481,0.668828,-0.120980,-1.588068,1.295206,1.060432,-1.096590

In [30]:
sample_scaled.info()

<class 'pandas.core.frame.DataFrame'>
Index: 80000 entries, 54075 to 81403
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Index                   80000 non-null  float64
 1   pH                      80000 non-null  float64
 2   Iron                    80000 non-null  float64
 3   Nitrate                 80000 non-null  float64
 4   Chloride                80000 non-null  float64
 5   Lead                    80000 non-null  float64
 6   Zinc                    80000 non-null  float64
 7   Color                   80000 non-null  float64
 8   Turbidity               80000 non-null  float64
 9   Fluoride                80000 non-null  float64
 10  Copper                  80000 non-null  float64
 11  Odor                    80000 non-null  float64
 12  Sulfate                 80000 non-null  float64
 13  Conductivity            80000 non-null  float64
 14  Chlorine                80000 non-null  float64
 15  Manganese               80000 non-null  float64
 16  Total Dissolved Solids  80000 non-null  float64
 17  Source                  80000 non-null  float64
 18  Water Temperature       80000 non-null  float64
 19  Air Temperature         80000 non-null  float64
 20  Month                   80000 non-null  float64
 21  Day                     80000 non-null  float64
 22  Time of Day             80000 non-null  float64
dtypes: float64(23)
memory usage: 14.6 MB